### ISSUE TITLE
Can’t display WordPress menu out of the box?

### ISSUE THREAD

**Issue by TechStacker** [colbyfayock/next-wordpress-starter#148] opened 2021-04-20 13:00 UTC
This glorious project seems to have everything you'd want for a Headless starter except for displaying the WP menu in Next.js via GraphQL. Or am I overlooking something? 

On this demo there are two menu items in the header nav https://next-wordpress-starter.netlify.app/docs/ — but I'm not sure if they are hardcoded in the demo app, or if they're created via GraphQL from the native WordPress Menu panel?  

I'm sorry if this functionality is already there, I just can't seem to find it 🤔

**Comment by colbyfayock** [comment] 2021-04-21 14:18
hey @TechStacker sorry i need to document this, but right now the way it works is it only pulls in pages with a menu order of > 0

https://github.com/colbyfayock/next-wordpress-starter/blob/476cb1b41b5c51c9a02afab91cf058f0a33f8b85/src/lib/pages.js#L71

the goal was to be able to give someone control of actually showing a page in the navigation as well as the order

I'd like to have menu support, i can't remember if I was having trouble figuring it out when looking into it, but i do have a ticket for it to try to work on

https://github.com/colbyfayock/next-wordpress-starter/issues/7

we would nee to be able to query a dynamic menu somehow

**Comment by colbyfayock** [comment] 2021-04-21 14:22
actually i just looked at my own project to see if it would come up in a query and it looks like it does so it's just a matter of implementing it in a way that makes sense, like managing how the locations work for doing so which wouldn't be too bad

![image](https://user-images.githubusercontent.com/1045274/115569606-6561e380-a28b-11eb-8ee0-9c2cc9347294.png)

**Comment by TechStacker** [comment] 2021-04-22 12:06
Appreciate your response @colbyfayock !  

> right now the way it works is it only pulls in pages with a menu order of > 0 

When I create pages and give them a value greater than 0, I get this error as soon as I click on the menu item for that page: 

```
Server Error
Error: A required parameter (slugParent) was not provided as a string in getStaticPaths for /[slugParent]/[[...slugChild]]
```

Can you replicate that error or is it just on my end? 🤔

**Comment by colbyfayock** [comment] 2021-04-24 02:43
thats strange - im not able to reproduce that

![image](https://user-images.githubusercontent.com/1045274/115944711-47f86980-a485-11eb-99be-4ba84d4cc545.png)

is your wordpress link public that i could plug it in locally?

**Comment by colbyfayock** [comment] 2021-04-25 21:21
closing this since we have #7 to track menu support, but let me know if you're still running into issues and i can try to play with it!

**Closed by colbyfayock** 2021-04-25 21:21 UTC

**Comment by colbyfayock** [comment] 2021-04-30 02:29
hey @TechStacker menus are supported now, at least 1 for primary navigation :)

https://github.com/colbyfayock/next-wordpress-starter/pull/150

README is updated to show how to configure
